Include e2e tests for `guaccollect`, `guacingest`, and ent (#1998)
* Included e2e tests for guaccollect, guacingest and ent

Signed-off-by: nathannaveen <42319948+nathannaveen@users.noreply.github.com>

* Fixing e2e

Signed-off-by: nathannaveen <42319948+nathannaveen@users.noreply.github.com>
Signed-off-by: Nathan Naveen <nathannaveen@Nathans-MacBook-Pro.local>

* Most Passing, but Deadlock Failing

Signed-off-by: Nathan Naveen <nathannaveen@Nathans-MacBook-Pro.local>

* Mostly Passing

Signed-off-by: Nathan Naveen <nathannaveen@Nathans-MacBook-Pro.local>

* Cleaning up

Signed-off-by: nathannaveen <42319948+nathannaveen@users.noreply.github.com>

* Working e2e

Signed-off-by: nathannaveen <42319948+nathannaveen@users.noreply.github.com>

* Revert changes to docker-compose.yml to match main branch

Signed-off-by: nathan naveen <nathannaveen@nathans-MacBook-Pro-2.local>

---------

Signed-off-by: nathannaveen <42319948+nathannaveen@users.noreply.github.com>
Signed-off-by: Nathan Naveen <nathannaveen@Nathans-MacBook-Pro.local>
Signed-off-by: nathan naveen <nathannaveen@nathans-MacBook-Pro-2.local>
Co-authored-by: Nathan Naveen <nathannaveen@Nathans-MacBook-Pro.local>
Co-authored-by: nathan naveen <nathannaveen@nathans-MacBook-Pro-2.local>

diff --git a/internal/testing/e2e/e2e b/internal/testing/e2e/e2e
--- a/internal/testing/e2e/e2e
+++ b/internal/testing/e2e/e2e
@@ -1,4 +1,4 @@
-#!/bin/bash
+﻿#!/bin/env bash
 
 #
 # Copyright 2023 The GUAC Authors.
@@ -17,8 +17,22 @@
 
 set -euf -o pipefail
 
-SCRIPT_DIR=$(cd $(dirname $0); pwd)
-GUAC_DIR=$(cd ${SCRIPT_DIR}/../../..; pwd)
+SCRIPT_DIR=$(cd "$(dirname "$0")"; pwd)
+GUAC_DIR=$(cd "${SCRIPT_DIR}"/../../..; pwd)
+
+LOG_DIR="${GUAC_DIR}/internal/testing/e2e/logs"
+LOG_FILE="${LOG_DIR}/logfile.log"
+SCHEMA_BACKUP="${LOG_DIR}/schema_backup.sql"
+
+export PGPASSWORD=$POSTGRES_PASSWORD
+
+# Create the log directory if it doesn't exist
+mkdir -p "$LOG_DIR"
+
+# Create the blobstore directory if it doesn't exist
+mkdir -p /tmp/blobstore
+
+echo "Script started" | tee -a "$LOG_FILE"
 
 guac_data_hash="254d737ebc42ca32f95033e93370f5427e3fce64"
 
@@ -34,12 +48,11 @@ popd
 popd
 
 echo @@@@ Starting up guac server in background
-go run "${GUAC_DIR}/cmd/guacgql" &
+go run "${GUAC_DIR}/cmd/guacgql" --gql-backend=ent &
 
 echo -n "Waiting for guac server to start"
-
 set +e
-for iteration in {1..36} ; do
+for _ in {1..36} ; do
   sleep 5
   curl -s http://localhost:8080/query >/dev/null 2>&1
   if [ $? -ne 7 ] ; then
@@ -53,56 +66,120 @@ echo
 curl -s http://localhost:8080/query >/dev/null 2>&1 || (echo "Guac server not running in time" && exit 1)
 echo "Guac server started"
 
-echo @@@@ Ingesting guac-data into server
-go run "${GUAC_DIR}/cmd/guacone" collect files "${GUAC_DIR}/guac-data/docs/"
+duplicate_schema() {
+  echo @@@@ Duplicating schema
+  pg_dump -h localhost -p 5432 -U guac -d guac -s > "$SCHEMA_BACKUP"
+}
 
-echo @@@@ Running osv certifier
-go run "${GUAC_DIR}/cmd/guacone" certifier osv
+restore_schema() {
+  echo @@@@ Restoring schema
+  psql -h localhost -p 5432 -U guac -d guac -f "$SCHEMA_BACKUP"
+}
+
+wipe_data() {
+  echo @@@@ Wiping data
+  local retries=5
+  local count=0
+  local success=false
+
+  while [ $count -lt $retries ]; do
+    psql -h localhost -p 5432 -U guac -d guac -c "DROP SCHEMA public CASCADE; CREATE SCHEMA public;" && success=true && break
+    count=$((count + 1))
+    echo "Retrying wipe_data ($count/$retries)..."
+    sleep 5
+  done
+
+  if [ "$success" = true ]; then
+    restore_schema
+  else
+    echo "Error: Failed to wipe data after $retries attempts" | tee -a "$LOG_FILE"
+    exit 1
+  fi
+}
+
+go run ${GUAC_DIR}"/cmd/guacingest" --add-vuln-on-ingest=true &
+go run ${GUAC_DIR}"/cmd/guacone" collect deps_dev -p &
+go run ${GUAC_DIR}"/cmd/guaccsub" &
+
+# Define ingestion commands
+declare -a ingestion_commands=(
+  "go run ${GUAC_DIR}/cmd/guacone collect files ${GUAC_DIR}/guac-data/docs/ --add-vuln-on-ingest=true"
+  "go run ${GUAC_DIR}/cmd/guaccollect files ${GUAC_DIR}/guac-data/docs/ --service-poll=false"
+)
+
+declare -A queryValues
+
+queryValues["PkgQ1"]='.packages |= sort'
+queryValues["PkgQ2"]='.packages[].namespaces |= sort'
+queryValues["PkgQ3"]='.packages[].namespaces |= sort_by(.namespace) | .packages[].namespaces[].names[].versions |= sort_by(.purl) | .packages[].namespaces[].names[].versions[].qualifiers |= sort_by(.key) | del(.. | .id?)'
+queryValues["PkgQ4"]='del(.. | .id?)'
+queryValues["IsDependencyQ1"]='.IsDependency |= sort'
+queryValues["IsDependencyQ2"]='del(.. | .id?) | del(.. | .origin?)'
+queryValues["PathQ1"]='del(.. | .id?) | del(.. | .origin?)'
+queryValues["OSVQ1"]='del(.. | .id?)'
+queryValues["CertifyVulnQ1"]='del(.. | .id?) | del(.. | .timeScanned?)'
+queryValues["ArtifactsQ1"]='.artifacts |= sort'
+queryValues["PkgQ9"]='.packages[].namespaces |= sort_by(.namespace) | .packages[].namespaces[].names[].versions |= sort_by(.id) | .packages[].namespaces[].names[].versions[].qualifiers |= sort_by(.key) | del(.. | .id?)'
+
+# Define an indexed array to maintain the order of the queries
+queryOrder=(
+  "PkgQ1"
+  "PkgQ2"
+  "PkgQ3"
+  "PkgQ4"
+  "IsDependencyQ1"
+  "IsDependencyQ2"
+  "PathQ1"
+  "OSVQ1"
+  "CertifyVulnQ1"
+  "ArtifactsQ1"
+  "PkgQ9"
+)
 
 queries="${GUAC_DIR}/demo/graphql/queries.gql"
 
-echo @@@@ Running queries and validating output
+duplicate_schema
 
-cat "$queries" | gql-cli http://localhost:8080/query -o PkgQ1 | jq ' .packages |= sort ' > "${GUAC_DIR}/gotPkgQ1.json"
-diff -u "${SCRIPT_DIR}/expectPkgQ1.json" "${GUAC_DIR}/gotPkgQ1.json"
+# Loop through ingestion commands
+for command in "${ingestion_commands[@]}"; do
+  echo @@@@ Running ingestion command: "$command" | tee -a "$LOG_FILE"
+  eval "$command"
+  go run ${GUAC_DIR}"/cmd/guacone" certifier osv -p=false
 
-cat "$queries" | gql-cli http://localhost:8080/query -o PkgQ2 | jq ' .packages[].namespaces |= sort ' > "${GUAC_DIR}/gotPkgQ2.json"
-diff -u "${SCRIPT_DIR}/expectPkgQ2.json" "${GUAC_DIR}/gotPkgQ2.json"
+  if [ $? -ne 0 ]; then
+    echo "Error: Command '$command' failed" | tee -a "$LOG_FILE"
+    exit 1
+  fi
 
-cat "$queries" | gql-cli http://localhost:8080/query -o PkgQ3 | jq ' .packages[].namespaces |= sort_by(.namespace) | .packages[].namespaces[].names[].versions |= sort_by(.id) | .packages[].namespaces[].names[].versions[].qualifiers |= sort_by(.key) | del(.. | .id?) ' > "${GUAC_DIR}/gotPkgQ3.json"
-diff -u "${SCRIPT_DIR}/expectPkgQ3.json" "${GUAC_DIR}/gotPkgQ3.json"
+  echo @@@@ Waiting
+  sleep 60
 
-cat "$queries" | gql-cli http://localhost:8080/query -o PkgQ4 | jq ' del(.. | .id?) '> "${GUAC_DIR}/gotPkgQ4.json"
-diff -u "${SCRIPT_DIR}/expectPkgQ4.json" "${GUAC_DIR}/gotPkgQ4.json"
+  echo @@@@ Running queries and validating output
 
-cat "$queries" | gql-cli http://localhost:8080/query -o IsDependencyQ1 | jq ' .IsDependency |= sort ' > "${GUAC_DIR}/gotIsDependencyQ1.json"
-diff -u "${SCRIPT_DIR}/expectIsDependencyQ1.json" "${GUAC_DIR}/gotIsDependencyQ1.json"
+  id1=$(gql-cli http://localhost:8080/query -o PkgQ5 < "$queries" | jq -r ' .packages[0].namespaces[0].names[0].id ')
+  id2=$(gql-cli http://localhost:8080/query -o PkgQ6 < "$queries" | jq -r ' .packages[0].namespaces[0].names[0].id ')
+  id3=$(gql-cli http://localhost:8080/query -o PkgQ7 < "$queries" | jq -r ' .packages[0].namespaces[0].names[0].id ')
+  id4=$(gql-cli http://localhost:8080/query -o PkgQ8 < "$queries" | jq -r ' .packages[0].namespaces[0].names[0].versions[0].id ')
 
-cat "$queries" | gql-cli http://localhost:8080/query -o IsDependencyQ2 | jq 'del(.. | .id?) | del(.. | .origin?)' > "${GUAC_DIR}/gotIsDependencyQ2.json"
-diff -u "${SCRIPT_DIR}/expectIsDependencyQ2.json" "${GUAC_DIR}/gotIsDependencyQ2.json"
+  for query in "${queryOrder[@]}"; do
+    echo @@@@ Running query "$query" | tee -a "$LOG_FILE"
+    if [ "$query" == "PathQ1" ]; then
+      gql-cli http://localhost:8080/query -o "$query" -V subject:"${id1}" target:"${id2}" < "$queries" | jq "${queryValues[$query]}" > "${GUAC_DIR}/got${query}.json"
+    else
+      gql-cli http://localhost:8080/query -o "$query" < "$queries" | jq "${queryValues[$query]}" > "${GUAC_DIR}/got${query}.json"
+    fi
+    diff -u "${SCRIPT_DIR}/expect${query}.json" "${GUAC_DIR}/got${query}.json" | tee -a "$LOG_FILE"
+  done
 
-id1=$(cat "$queries" | gql-cli http://localhost:8080/query -o PkgQ5 | jq -r ' .packages[0].namespaces[0].names[0].id ')
-id2=$(cat "$queries" | gql-cli http://localhost:8080/query -o PkgQ6 | jq -r ' .packages[0].namespaces[0].names[0].id ')
+  # Run the additional query that doesn't follow the same format
+  echo @@@@ Running query path.py | tee -a "$LOG_FILE"
+  "${GUAC_DIR}/demo/graphql/path.py" "$id3" "$id4" | tail -n +2 | jq 'del(.. | .id?) | del(.. | .origin?) | del(.. | .qualifiers?)' > "${GUAC_DIR}/gotPathPy.json"
+  diff -u "${SCRIPT_DIR}/expectPathPy.json" "${GUAC_DIR}/gotPathPy.json" | tee -a "$LOG_FILE"
 
-cat "$queries" | gql-cli http://localhost:8080/query -o PathQ1 -V subject:${id1} target:${id2} | jq 'del(.. | .id?) | del(.. | .origin?)' > "${GUAC_DIR}/gotPathQ1.json"
-diff -u "${SCRIPT_DIR}/expectPathQ1.json" "${GUAC_DIR}/gotPathQ1.json"
+  echo @@@@ Fully ingested command: "$command" | tee -a "$LOG_FILE"
 
-cat "$queries" | gql-cli http://localhost:8080/query -o OSVQ1 | jq 'del(.. | .id?)' > "${GUAC_DIR}/gotOSVQ1.json"
-diff -u "${SCRIPT_DIR}/expectOSVQ1.json" "${GUAC_DIR}/gotOSVQ1.json"
-
-cat "$queries" | gql-cli http://localhost:8080/query -o CertifyVulnQ1 | jq 'del(.. | .id?) | del(.. | .timeScanned?)' > "${GUAC_DIR}/gotCertifyVulnQ1.json"
-diff -u "${SCRIPT_DIR}/expectCertifyVulnQ1.json" "${GUAC_DIR}/gotCertifyVulnQ1.json"
-
-id3=$(cat "$queries" | gql-cli http://localhost:8080/query -o PkgQ7 | jq -r ' .packages[0].namespaces[0].names[0].id ')
-id4=$(cat "$queries" | gql-cli http://localhost:8080/query -o PkgQ8 | jq -r ' .packages[0].namespaces[0].names[0].versions[0].id ')
-
-"${GUAC_DIR}/demo/graphql/path.py" $id3 $id4 | tail -n +2 | jq 'del(.. | .id?) | del(.. | .origin?) | del(.. | .qualifiers?)' > "${GUAC_DIR}/gotPathPy.json"
-diff -u "${SCRIPT_DIR}/expectPathPy.json" "${GUAC_DIR}/gotPathPy.json"
-
-cat "$queries" | gql-cli http://localhost:8080/query -o ArtifactsQ1 | jq ' .artifacts |= sort '> "${GUAC_DIR}/gotArtifactsQ1.json"
-diff -u "${SCRIPT_DIR}/expectArtifactsQ1.json" "${GUAC_DIR}/gotArtifactsQ1.json"
-
-cat "$queries" | gql-cli http://localhost:8080/query -o PkgQ9 | jq ' .packages[].namespaces |= sort_by(.namespace) | .packages[].namespaces[].names[].versions |= sort_by(.id) | .packages[].namespaces[].names[].versions[].qualifiers |= sort_by(.key) | del(.. | .id?) ' > "${GUAC_DIR}/gotPkgQ9.json"
-diff -u "${SCRIPT_DIR}/expectPkgQ9.json" "${GUAC_DIR}/gotPkgQ9.json"
+  # Wipe data after each ingestion command
+  wipe_data
+done
 
 # Note: graphql_playground is left running, CI will clean it up
